# This is the default configuration file for the
# SEL-751-Arc-Flash-Speed-Up tool.
# https://github.com/danyill/SEL-751-Arc-Flash-Speed-Up

# This file is parsed to produce relay settings and IEC 61850 configuration
# files.

# This file is written in TOML v0.4.0
# https://github.com/toml-lang/toml/blob/v0.4.0/README.md

# The lines commented with a # are illustrative. A full, commented out sample
# configuration is given below.

# BEGINNING OF SAMPLE CONFIGURATION
# The lines below are just versioning to ensure processing in the program is correct
# [ConfigInfo]
# ArcFlashVersion = "30Nov2016"
# ArcFlashSpeedUpVersion = "30Nov2016"

# BEGINNING OF SAMPLE CONFIGURATION
#[Primary]
# Primary information for a bus is to be entered from left to right from a
# SLD and is given following the section in square brackets [Primary]

# In square brackets the first bus name is provided after the word Bus
# This is followed by a comma delimited list of all bays associated with the
# bus.
#  * bus couplers are not included.
#  * under the parameter BayNames from left to right the baynames should be
#    entered.
#  * under the parameter BayTypes only 'Feeder', 'Incomer' or 'Riser' should be
#    entered. These are case-insensitive and may be abbreviated to 'f', 'i' or
#    'r'.
#  * under the parameter SwitchgearType only 'GHA', 'Fluair' and 'LMVP' should
#    be entered.
# [Bus]
# Name = 'A1'
# BayNames =  ['ERE0012','ERE0022','ERE0032','ERE0042','ERE0052','ERE0062','ERE0072','ERE0082']
# BayTypes =  ['feeder','feeder','feeder','feeder','incomer','feeder','feeder','feeder']
# SwitchgearType = GHA

# Enter as many buses as desired. All buses will be the same rdb file and
# also the same scd file. So choose one configuration file per connected
# buses and voltage level.
#[Bus]
#Name = 'A2'
# BayNames = ['ERE00102','ERE0112','ERE0122','ERE0132','ERE0142','ERE0152','ERE0162','ERE0182']
# BayTypes = ['riser','feeder','feeder','incomer','feeder','feeder','feeder','feeder']
# SwitchgearType = 'GHA'

# Now couplers are entered.
# Start a new section in square brackets with Coupler followed by the
# coupled buses with a space in between. Repeat for as many couplers as
# necessary. Then enter the BayName and SwitchgearType as above.
#[Coupler]
#From = 'A1'
#To = 'A2'
#BayName = 'ERE00098'
#SwitchgearType = 'GHA'

#[Secondary]

# Now input information about the secondary system, after a section in square
# brackets beginning [Secondary]. Most of this is already prescribed by virtue
# of the standard file. However the following parameters need to be chosen.

# If using default relay names corresponding to bay names:
#  * BayName + P3 for feeders, incomers and risers,
#  * BayName + P4 for couplers
# Then just leave this at the defaults using the directive:
# RelayNames Automatic
# The script will determine from the bayname and the ending digit (
#  * '8'=coupler='P4',
#  * anything else='P3'

# Otherwise you need to specify for each bay the relay name respectively
# on the different lines.

# Comment the above directive and uncomment this line to see an example:
# BayNames =  ['ERE0012','ERE0022','ERE0032','ERE0042','ERE0052','ERE0062','ERE0072','ERE0082','ERE0098','ERE00102','ERE0112','ERE0122','ERE0132','ERE0142','ERE0152','ERE0162','ERE0182']
# RelayNames =  ['ERE0012P3','ERE0022P3','ERE0032P3','ERE0042P3','ERE0052P3','ERE0062P3','ERE0072P3','ERE0082P3','ERE0098P4','ERE00102P3',ERE0112P3','ERE0122P3','ERE0132P3','ERE0142P3','ERE0152P3','ERE0162P3','ERE0182P3']

# Finally the only things remaining to be specified are:
#  * if the relay watchdog is to be used
#  * ethernet settings
#  * DNP3 settings

# To do this you must have a BayNames directive in place, so the file must
# have:
#
# BayNames
#
# followed by
#
# RelayNames

# Then in CSV format put the corresponding value for each relay into the
# following parameters. If there is only a single value given for any relay,
# this same value will be used for all relays.

# BayNames
# RelayNames = 'Automatic'
# IPAddress = ['192.168.1.12','192.168.1.22','192.168.1.32','192.168.1.42','192.168.1.52','192.168.1.62','192.168.1.72','192.168.1.82','192.168.1.98','192.168.1.102','192.168.1.112','192.168.1.122','192.168.1.132','192.168.1.142','192.168.1,152','192.168.1.162','192.168.1.172','192.168.1.182']

# What DNP address does each relay have? If one value enter this, otherwise
# enter a value for each bay in an array.
# DNPAddress = 100
# Same for IP addresses
# DNPIPAddress = [12,22,32,42,52,62,72,82,98,102,112,132,142,152,162,172,182]
# Is the watchdog of the Prot1 relay wired to the arc flash relay?
# WatchDogWired = true
# SubnetMask = '255.255.255.0'

# The MAC directive indicates that MAC addresses for transmitted GOOSE
# messages should begin from this particular value, if it is necessary
# to prescribe each MAC address, then they should be comma delimited.
# If this directive is missing, then MAC addresses will begin from:
# 01-0C-CD-01-00-01.
# MAC = '01-0C-CD-01-00-01'

# END OF SAMPLE CONFIGURATION

# Directives below should be entered without the '#' indicating a comment.
# An exmaple configuration based on the above is provided. Enjoy!

[ConfigInfo]
ArcFlashVersion = "30Nov2016"
ArcFlashSpeedUpVersion = "30Nov2016"

[Primary]
[[Primary.Bus]]
Name = 'A1'
BayNames =  ['ERE0012','ERE0022','ERE0032','ERE0042','ERE0052','ERE0062','ERE0072','ERE0082']
BayTypes =  ['feeder','feeder','feeder','feeder','incomer','feeder','feeder','feeder']
SwitchgearType = 'GHA'

[[Primary.Bus]]
Name = 'A2'
BayNames = ['ERE00102','ERE0112','ERE0122','ERE0132','ERE0142','ERE0152','ERE0162','ERE0182']
BayTypes = ['riser','feeder','feeder','incomer','feeder','feeder','feeder','feeder']
SwitchgearType = 'GHA'

[[Primary.Coupler]]
From = 'A1'
To = 'A2'
BayName = 'ERE00098'
SwitchgearType = 'GHA'

[Secondary]
BayNames =  ['ERE0012','ERE0022','ERE0032','ERE0042','ERE0052','ERE0062','ERE0072','ERE0082','ERE0098','ERE00102','ERE0112','ERE0122','ERE0132','ERE0142','ERE0152','ERE0162','ERE0182']
RelayNames =  ['ERE0012P3','ERE0022P3','ERE0032P3','ERE0042P3','ERE0052P3','ERE0062P3','ERE0072P3','ERE0082P3','ERE0098P4','ERE00102P3','ERE0112P3','ERE0122P3','ERE0132P3','ERE0142P3','ERE0152P3','ERE0162P3','ERE0182P3']
IPAddresses = ['192.168.1.12','192.168.1.22','192.168.1.32','192.168.1.42','192.168.1.52','192.168.1.62','192.168.1.72','192.168.1.82','192.168.1.98','192.168.1.102','192.168.1.112','192.168.1.122','192.168.1.132','192.168.1.142','192.168.1.152','192.168.1.162','192.168.1.172','192.168.1.182']
DNPAddress = 100
DNPIPAddress = [12,22,32,42,52,62,72,82,98,102,112,132,142,152,162,172,182]
WatchDogWired = true
SubnetMask = '255.255.255.0'
MAC = '01-0C-CD-01-00-01'
