= SEL-751-Arc-Flash-Speed-Up

Tool to speed up settings development for Transpower standard arc-flash protection 

== Installation

This tool:
* uses Python (either 2.7.x or 3.5.x). 
* uses the standard www.transpower.co.nz{Transpower} SEL-751 arc-flash protection package.

The purpose of this tool is to:
* allow efficient production of arc-flash protection settings.
* allow efficient production of arc-flash IEC 61850 GOOSE "virtual wiring".
* save people from having to carry out mind-numbingly tedious minor changes.
* save people from making silly mistakes while making minor changes.

== How To Use

. Ensure Python is installed (https://www.python.org/downloads/{how?})
. Ensure Git is installed (https://git-scm.com/book/en/v2/Getting-Started-Installing-Git{how?})
. Ensure The Transpower standard package is readily accessible.
. Clone this repository (`git clone https://github.com/danyill/SEL-751-Arc-Flash-Speed-Up`)
. Copy the standard package into the root folder of this repository.
. Copy the default configuration file (`default.config`) to something specific to your project.
. Edit the new configuration file. Instructions are included in the file.
. Run the script `automate.py` on the configuration file. Something like `automate.py my_configuration_file.txt`.
. In the `output` folder, you will now find:
.* an `rdb` file
.* an `scd` file
.* a `selaprj` file
. Carry out some checks to see that these look correct.

== How this tool works?

It's not very hard. Look at the code and learn something new.

1. Update the TID. For coupler and riser relays append COUPLER and RISER, e.g. ERE2042 COUPLER.
2. Disable any unused sensors using the AFSENSn setting as detailed in section 4.5.2Error: Reference source not found.
3. Set LT01, LT02 and LT03 according to Table  3 .4 andError: Reference source not found Table  3 .5 and the logic diagram.
4. If the Prot1 relay watchdog  is not wired into this relay, set  SV10 to NA #NOT IN302 #PROT 1 WATCHDOG to disable the front panel alarm.
5. Update Ethernet settings:
a. IPADDR
b. SUBNETM
c. DEFRTR
d. TCBAN
e. FTPCBAN
6. Update SCADA related settings such as DNP addresses:
a. DNPADR
b. DNPIP1

== How to Contribute
* Don't like how this works? File an issue.
* Think you can do better? File an issue making a suggestion.
* Want to modify this to make it better? Submit a pull request.


